import sqlite3
from PyQt6.QtGui import QPixmap
from PyQt6.QtCore import QByteArray
from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(1240, 576)
        Form.setToolTipDuration(0)
        Form.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.gridLayout_14 = QtWidgets.QGridLayout(Form)
        self.gridLayout_14.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_14.setHorizontalSpacing(10)
        self.gridLayout_14.setVerticalSpacing(30)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.groupbox_0 = QtWidgets.QGroupBox(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupbox_0.sizePolicy().hasHeightForWidth())
        self.groupbox_0.setSizePolicy(sizePolicy)
        self.groupbox_0.setMinimumSize(QtCore.QSize(600, 250))
        self.groupbox_0.setMaximumSize(QtCore.QSize(16777215, 250))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupbox_0.setFont(font)
        self.groupbox_0.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupbox_0.setFlat(False)
        self.groupbox_0.setObjectName("groupbox_0")
        self.gridLayout = QtWidgets.QGridLayout(self.groupbox_0)
        self.gridLayout.setObjectName("gridLayout")
        self.combo_04 = QtWidgets.QComboBox(parent=self.groupbox_0)
        self.combo_04.setMinimumSize(QtCore.QSize(275, 30))
        self.combo_04.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.combo_04.setFont(font)
        self.combo_04.setObjectName("combo_04")
        self.gridLayout.addWidget(self.combo_04, 3, 1, 1, 1)
        self.combo_05 = QtWidgets.QComboBox(parent=self.groupbox_0)
        self.combo_05.setMinimumSize(QtCore.QSize(275, 30))
        self.combo_05.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.combo_05.setFont(font)
        self.combo_05.setObjectName("combo_05")
        self.gridLayout.addWidget(self.combo_05, 4, 1, 1, 1)
        self.combo_03 = QtWidgets.QComboBox(parent=self.groupbox_0)
        self.combo_03.setMinimumSize(QtCore.QSize(275, 30))
        self.combo_03.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.combo_03.setFont(font)
        self.combo_03.setObjectName("combo_03")
        self.gridLayout.addWidget(self.combo_03, 2, 1, 1, 1)
        self.label_03 = QtWidgets.QLabel(parent=self.groupbox_0)
        self.label_03.setMinimumSize(QtCore.QSize(225, 30))
        self.label_03.setMaximumSize(QtCore.QSize(225, 30))
        self.label_03.setTabletTracking(False)
        self.label_03.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_03.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_03.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_03.setObjectName("label_03")
        self.gridLayout.addWidget(self.label_03, 2, 0, 1, 1)
        self.label_04 = QtWidgets.QLabel(parent=self.groupbox_0)
        self.label_04.setMinimumSize(QtCore.QSize(225, 30))
        self.label_04.setMaximumSize(QtCore.QSize(225, 30))
        self.label_04.setTabletTracking(False)
        self.label_04.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_04.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_04.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_04.setObjectName("label_04")
        self.gridLayout.addWidget(self.label_04, 3, 0, 1, 1)
        self.label_05 = QtWidgets.QLabel(parent=self.groupbox_0)
        self.label_05.setMinimumSize(QtCore.QSize(225, 30))
        self.label_05.setMaximumSize(QtCore.QSize(225, 30))
        self.label_05.setTabletTracking(False)
        self.label_05.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_05.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_05.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_05.setObjectName("label_05")
        self.gridLayout.addWidget(self.label_05, 4, 0, 1, 1)
        self.label_02 = QtWidgets.QLabel(parent=self.groupbox_0)
        self.label_02.setMinimumSize(QtCore.QSize(225, 30))
        self.label_02.setMaximumSize(QtCore.QSize(225, 30))
        self.label_02.setTabletTracking(False)
        self.label_02.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_02.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_02.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_02.setObjectName("label_02")
        self.gridLayout.addWidget(self.label_02, 1, 0, 1, 1)
        self.combo_02 = QtWidgets.QComboBox(parent=self.groupbox_0)
        self.combo_02.setMinimumSize(QtCore.QSize(275, 30))
        self.combo_02.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.combo_02.setFont(font)
        self.combo_02.setObjectName("combo_02")
        self.gridLayout.addWidget(self.combo_02, 1, 1, 1, 1)
        self.combo_01 = QtWidgets.QComboBox(parent=self.groupbox_0)
        self.combo_01.setMinimumSize(QtCore.QSize(275, 30))
        self.combo_01.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.combo_01.setFont(font)
        self.combo_01.setObjectName("combo_01")
        self.gridLayout.addWidget(self.combo_01, 0, 1, 1, 1)
        self.label_01 = QtWidgets.QLabel(parent=self.groupbox_0)
        self.label_01.setMinimumSize(QtCore.QSize(225, 30))
        self.label_01.setMaximumSize(QtCore.QSize(225, 30))
        self.label_01.setTabletTracking(False)
        self.label_01.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_01.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_01.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_01.setObjectName("label_01")
        self.gridLayout.addWidget(self.label_01, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.groupbox_0, 0, 0, 1, 1)
        self.groupbox_1 = QtWidgets.QGroupBox(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupbox_1.sizePolicy().hasHeightForWidth())
        self.groupbox_1.setSizePolicy(sizePolicy)
        self.groupbox_1.setMinimumSize(QtCore.QSize(600, 82))
        self.groupbox_1.setMaximumSize(QtCore.QSize(16777215, 82))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupbox_1.setFont(font)
        self.groupbox_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupbox_1.setFlat(False)
        self.groupbox_1.setObjectName("groupbox_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupbox_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.combo_11 = QtWidgets.QComboBox(parent=self.groupbox_1)
        self.combo_11.setMinimumSize(QtCore.QSize(275, 30))
        self.combo_11.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.combo_11.setFont(font)
        self.combo_11.setObjectName("combo_11")
        self.gridLayout_2.addWidget(self.combo_11, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(parent=self.groupbox_1)
        self.label_11.setMinimumSize(QtCore.QSize(225, 30))
        self.label_11.setMaximumSize(QtCore.QSize(225, 30))
        self.label_11.setTabletTracking(False)
        self.label_11.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_11.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.groupbox_1, 1, 0, 1, 1)
        self.groupbox_2 = QtWidgets.QGroupBox(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupbox_2.sizePolicy().hasHeightForWidth())
        self.groupbox_2.setSizePolicy(sizePolicy)
        self.groupbox_2.setMinimumSize(QtCore.QSize(600, 332))
        self.groupbox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupbox_2.setFont(font)
        self.groupbox_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupbox_2.setFlat(False)
        self.groupbox_2.setObjectName("groupbox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupbox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.groupbox_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_solution = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_solution.setMinimumHeight(2000)
        self.label_solution.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)  # Позволяет метке растягиваться по ширине
        self.label_solution.setAlignment(QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_solution.setObjectName("label_solution")
        layout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        layout.addWidget(self.label_solution)
        self.scrollAreaWidgetContents.setLayout(layout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.groupbox_2, 0, 1, 3, 1)
        self.gridLayout_14.setColumnStretch(1, 1)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.loadData()
        self.combo_01.currentIndexChanged.connect(self.update_combo_02)  # Signal for updated selection
        self.combo_02.currentIndexChanged.connect(self.update_combo_03)  # Signal for updated selection
        self.combo_03.currentIndexChanged.connect(self.update_combo_04)  # Signal for updated selection
        self.combo_04.currentIndexChanged.connect(self.update_combo_05)  # Signal for updated selection
        self.combo_05.currentIndexChanged.connect(self.update_combo_11)  # Signal for updated selection
        self.combo_11.currentIndexChanged.connect(self.loadImage)  # Signal for updated selection

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupbox_0.setTitle(_translate("Form", "ПАРАМЕТРЫ РАЗРУШЕНИЯ"))
        self.label_03.setText(_translate("Form", "Расположение на конструкции:"))
        self.label_04.setText(_translate("Form", "Зона расположения:"))
        self.label_05.setText(_translate("Form", "Дополнительные параметры:"))
        self.label_02.setText(_translate("Form", "Глубина разрушения:"))
        self.label_01.setText(_translate("Form", "Тип разрушения:"))
        self.groupbox_1.setTitle(_translate("Form", " УСЛОВИЯ ПРОИЗВОДСТВА РАБОТ"))
        self.label_11.setText(_translate("Form", "Особенности производства работ:"))
        self.groupbox_2.setTitle(_translate("Form", "УНИФИЦИРОВАННОЕ РЕШЕНИЕ"))
        # self.label_solution.setText(_translate("Form", "TextLabel"))

    def loadData(self):
        conn = sqlite3.connect("data.sqlite3")
        cursor = conn.cursor()
        cursor.execute("SELECT DISTINCT Type FROM Parameters")
        rows = cursor.fetchall()
        self.combo_01.clear()
        for row in rows:
            self.combo_01.addItem(row[0])
        conn.close()

    def update_combo_02(self):
        selected_value = self.combo_01.currentText()
        conn = sqlite3.connect("data.sqlite3")
        cursor = conn.cursor()
        cursor.execute("SELECT DISTINCT Depth FROM Parameters WHERE Type = ?",
                       (selected_value,))
        rows = cursor.fetchall()
        self.combo_02.clear()
        for row in rows:
            self.combo_02.addItem(row[0])
        conn.close()

    def update_combo_03(self):
        selected_value = self.combo_02.currentText()
        conn = sqlite3.connect("data.sqlite3")
        cursor = conn.cursor()
        cursor.execute("SELECT DISTINCT Location FROM Parameters WHERE Depth = ?",
                       (selected_value,))
        rows = cursor.fetchall()
        self.combo_03.clear()
        for row in rows:
            self.combo_03.addItem(row[0])
        conn.close()

    def update_combo_04(self):
        selected_value = self.combo_03.currentText()
        conn = sqlite3.connect("data.sqlite3")
        cursor = conn.cursor()
        cursor.execute("SELECT DISTINCT Zone FROM Parameters WHERE Location = ?",
                       (selected_value,))
        rows = cursor.fetchall()
        self.combo_04.clear()
        for row in rows:
            self.combo_04.addItem(row[0])
        conn.close()

    def update_combo_05(self):
        selected_value = self.combo_04.currentText()
        conn = sqlite3.connect("data.sqlite3")
        cursor = conn.cursor()
        cursor.execute("SELECT DISTINCT Option FROM Parameters WHERE Zone = ?",
                       (selected_value,))
        rows = cursor.fetchall()
        self.combo_05.clear()
        for row in rows:
            self.combo_05.addItem(row[0])
        conn.close()

    def update_combo_11(self):
        selected_value = self.combo_05.currentText()
        conn = sqlite3.connect("data.sqlite3")
        cursor = conn.cursor()
        cursor.execute("SELECT DISTINCT Сases FROM Parameters WHERE Option = ?",
                       (selected_value,))
        rows = cursor.fetchall()
        self.combo_11.clear()
        for row in rows:
            self.combo_11.addItem(row[0])
        conn.close()

    def loadImage(self):
        selected_item = self.combo_11.currentText()
        conn = sqlite3.connect("data.sqlite3")
        cursor = conn.cursor()
        cursor.execute("SELECT Img FROM Parameters WHERE Сases = ?", (selected_item,))
        result = cursor.fetchone()
        if result and result[0]:
            image_data = result[0]
            pixmap = QByteArray(image_data)
            q_pixmap = QPixmap()
            q_pixmap.loadFromData(pixmap)
            scaled_pixmap = q_pixmap.scaled(self.label_solution.size(),
                                            QtCore.Qt.AspectRatioMode.KeepAspectRatio,
                                            QtCore.Qt.TransformationMode.SmoothTransformation)
            self.label_solution.setPixmap(scaled_pixmap)
            self.label_solution.setFixedHeight(scaled_pixmap.height())

        cursor.close()
        conn.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
